# Generated by Django 5.0.8 on 2024-08-07 09:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app1", "0002_sqltoken"),
    ]

    operations = [
        migrations.CreateModel(
            name="HealthRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("age", models.IntegerField()),
                ("sex", models.IntegerField()),
                ("cp", models.IntegerField()),
                ("trestbps", models.IntegerField()),
                ("chol", models.IntegerField()),
                ("fbs", models.IntegerField()),
                ("restecg", models.IntegerField()),
                ("thalach", models.IntegerField()),
                ("exang", models.IntegerField()),
                ("slope", models.IntegerField()),
                ("ca", models.IntegerField()),
                ("thal", models.IntegerField()),
                ("new_oldpeak", models.IntegerField()),
                ("result", models.IntegerField(blank=True)),
            ],
        ),
    ]
